# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregate_cpp <- function(values, groups, levelgroup) {
    .Call('_ctepi_aggregate_cpp', PACKAGE = 'ctepi', values, groups, levelgroup)
}

ldbudboptimCpp <- function(z_values, F1, F2, F3, F4, x_limit, y_limit, delta = 0.1, sopY = NULL) {
    .Call('_ctepi_ldbudboptimCpp', PACKAGE = 'ctepi', z_values, F1, F2, F3, F4, x_limit, y_limit, delta, sopY)
}

masaCpp <- function(matriz) {
    .Call('_ctepi_masaCpp', PACKAGE = 'ctepi', matriz)
}

